### ISSUE TITLE
Digital archiving in PMB?

### ISSUE THREAD

**Issue by cfggns** [alternativelibraries/website#11]
Basic version could be fields with links to external zine pdfs. 
There might be some specific support for it in PMB, but I don't think so. That could be confirmed though.

**Comment by mach-o** [comment]
Audiobooks were the other medium that came up, so mp3/ogg would be nice too. I mentioned radio4all.net, but it seems they [only have a few of these](http://radio4all.net/index.php/series/Audiobooks), though maybe we could still use it to upload/mirror Audiobooks we create or find on other less-reliable sites.

**Comment by qpirgconcordialibrary** [comment]
i'd like to put in e-books, library genesis link, and a project muse account onto the database

**Comment by qpirgconcordialibrary** [comment]
Okay, for the library genesis link there is a different issue: #21 
For e-books in the catalogue, we wanted to experiment with this but the internet is cutting out too much:
Administration > Electronics Documents > List of upload folders

The other thing we tested (and it was easy!) after having created new record, or when editing an existing record, there is a button to "Add electronic copy" (next to the regular "Add copy" button). 

Add location (e.g. qpirg concordia) for groups data,

then upload file.

**Comment by cfggns** [comment]
I think the "Add electronic copy" discovery pretty much solves this issue! I don't think the "uploads folder" feature we were trying to test is likely to be very relevant. 

This is one thing that would definitely be worth documenting in the wiki, I think there is a lot of potential in the future for linking our books to free online copies :)
