### ISSUE TITLE
forgot password problem

### ISSUE THREAD

**Issue by estefaniaqpirg** [alternativelibraries/website#25]
it was brought to my attention that the forgot password step was not working correctly, apparently instead of sending a password it sent the username. I don't know if there is a way of knowing how it works or how can it be fixed.

PS. I also tried to use this feature but never got an email back

**Comment by estefaniaqpirg** [comment]
I have tested the forgot password feature, without having an actual password. It sends just the username however, it is enough to login to the website and change it (obtain a new password).

**Comment by mach-o** [comment]
Is this a bug or a feature? How should it behave if you don't have a password? Or is the idea is that the system shouldn't let you create an account without a password?

**Comment by estefaniaqpirg** [comment]
its a feature. The idea is that it will send you your username and maybe? (I'm not sure) a temporary password or your actual password. However, I have realized that some users might actually not have a password, therefore, it just sends the username. But you can actually log in and change your password with just your username.

**Comment by mach-o** [comment]
Ok great thanks! So is this issue ready to be closed?

**Comment by estefaniaqpirg** [comment]
I think the only thing remaining is that every time I have tried it to send me my password to my yahoo mail it does not, I'm not sure why (it worked with my gmail one though). But the main issue is resolved
