### ISSUE TITLE
Public identification of who has checked out books?

### ISSUE THREAD

**Issue by cfggns** [alternativelibraries/website#8]
At the AMUSE library committee meeting it was mentioned that someone thought they had seen member IDs next to the books that were checked out, from a public perspective of the website. This should be urgently confirmed because if it is the case it is a breach of privacy that will be fixed asap.

**Comment by mach-o** [comment]
It's also quite possible that I saw this over a year ago, on the old site. Still worth confirming, in any event.

**Comment by cfggns** [comment]
I just did a test of this. While logged into PMB I found a book that was currently loaned out. Then I logged out of the site and did a search through the OPAC for that book. I could see that it was loaned out, but the only details listed under "Status" were "Due for return by 08/22/2016". So I don't think there is any info about the person who borrowed the book leaking here. If someone else finds it on a different part of the public site that I'm missing then let me know! For now I will close this issue.
